# Ranks for /rankup
# Simply put the group name and the price to rank up.
# Case-sensitive!
# Please put the first rank (lowest) first in the list.
# The last rank (highest) should be last.
# Remember, don't include commas in your prices!
# Also, remember to include your default rank first (any price will work)
# So, if your default rank is Guest, put it first.
ranks:
  Guest: 0
  Member: 100
  VIP: 500
  AwesomePantsExtreme: 1500