name: RankUp
author: jkcclemens
website: http://dev.royaldev.org/
depend: [Vault]
main: org.royaldev.rankup.RankUp
version: 0.0.1

commands:
  rankup:
    description: Ranks you up if you've the required money.
    aliases: [ru]
    usage: /<command> (reload)

permissions:
  rankup.rankup:
    description: Allows you to use /rankup.
    default: op
  rankup.admin:
    description: Allows you to use /rankup reload.
    default: op